# Generated by Django 4.2.7 on 2024-02-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_customer_first_name_remove_customer_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='last_name',
        ),
    ]
