# Generated by Django 4.2.7 on 2024-02-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_administrator_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='last_name',
        ),
    ]
