# Generated by Django 5.0.1 on 2024-02-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_technician_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
