# Generated by Django 5.0.1 on 2024-02-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
